# Generated by Django 3.2.7 on 2021-12-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.submission')),
                ('Title', models.CharField(max_length=128)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            bases=('blog.submission',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.submission')),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            bases=('blog.submission',),
        ),
    ]
